# permissions for end users to view rpaasinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpaasinstance-viewer-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstances/status
  verbs:
  - get
