# permissions for end users to edit rpaasinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpaasinstance-editor-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstances/status
  verbs:
  - get
