apiVersion: extensions.tsuru.io/v1alpha1
kind: RpaasInstance
metadata:
  name: example-rpaasinstance
spec:
  replicas: 1
  planName: example-rpaasplan
  locations:
  - config:
      value: "location / { echo hello world; }"
      kind: Inline
