apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpaas-api
  labels:
    name: rpaas-api
spec:
  selector:
    matchLabels:
      name: rpaas-api
  replicas: 1
  template:
    metadata:
      labels:
        name: rpaas-api
    spec:
      containers:
      - name: rpaas-api
        image: tsuru/rpaas-api
        ports:
        - name: api
          containerPort: 9999
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: api
      serviceAccountName: api
      terminationGracePeriodSeconds: 10
